quarkus.datasource.db-kind=postgresql

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
#quarkus.hibernate-orm.log.sql=true

quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.clustered=true

quarkus.scheduler.start-mode=forced

quarkus.websocket.max-frame-size=102400

quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

